name: 'antokolsky_service'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U antokolsky -d antokolsky", "--quiet" ]
      interval: 10s
      timeout: 50s
      retries: 3
      start_period: 5s
    env_file:
      - ./.env

  backend:
    container_name: backend_container
    image: databorodata/antokolsky_backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - static_backend:/static_files
      - landing_media:/app/media

  frontend:
    container_name: frontend_container
    image: databorodata/antokolsky_front:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_backend:/frontend_static
  
  landing:
    container_name: landing_container
    image: databorodata/antokolsky_landing:latest
    command: cp -r /app/dist/. /landing_static/
    volumes:
      - landing_static:/landing_static

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_backend:/static_files
      - landing_static:/landing_static
      - landing_media:/landing_media
    depends_on:
      - frontend
      - backend
      - postgres
      - landing

volumes:
  postgres_data:
  static_backend:
  landing_static:
  landing_media: